// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNjBPNbZGejW5wUym9wt4UtgWARSjfR_E',
    appId: '1:155236721207:web:512f0841bc25c16e5f95b2',
    messagingSenderId: '155236721207',
    projectId: 'pcd2023-fae18',
    authDomain: 'pcd2023-fae18.firebaseapp.com',
    storageBucket: 'pcd2023-fae18.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj6C2VyxD-gCdX7lbNkVUlLPZovucKShs',
    appId: '1:155236721207:android:e5fd0ed5f57836505f95b2',
    messagingSenderId: '155236721207',
    projectId: 'pcd2023-fae18',
    storageBucket: 'pcd2023-fae18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsnSlLn_zf-iA-5gBMhlKpLfWRr2UHJqQ',
    appId: '1:155236721207:ios:59287104937928955f95b2',
    messagingSenderId: '155236721207',
    projectId: 'pcd2023-fae18',
    storageBucket: 'pcd2023-fae18.appspot.com',
    iosClientId: '155236721207-13lu2dnrtdod77ohms9qa3dul2k4gm2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.wellbeing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsnSlLn_zf-iA-5gBMhlKpLfWRr2UHJqQ',
    appId: '1:155236721207:ios:59287104937928955f95b2',
    messagingSenderId: '155236721207',
    projectId: 'pcd2023-fae18',
    storageBucket: 'pcd2023-fae18.appspot.com',
    iosClientId: '155236721207-13lu2dnrtdod77ohms9qa3dul2k4gm2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.wellbeing',
  );
}
